# Generated by Django 4.2.1 on 2023-05-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "managed": True,
                "verbose_name": "User",
                "verbose_name_plural": "User",
            },
        ),
        migrations.AlterModelTable(
            name="user",
            table="auth_users",
        ),
    ]
