# Generated by Django 4.2 on 2023-04-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0002_category_delete_mymodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
    ]
